//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParafiaTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParafiaTest.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Gra internetowa Parafia.biz - podbij wirtualną  rzeczywistość - gra przeglądarkowa przez www&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;link href=&quot;https://plus.google.com/102903768040082646276&quot; rel=&quot;publisher&quot;/&gt;
        ///    &lt;meta property=&quot;og:site_name&quot; content=&quot;Parafia.biz&quot; /&gt;
        ///	&lt;meta property=&quot;og:title&quot; content=&quot;Parafia.biz&quot; /&gt;
        ///	&lt;meta property=&quot;og:description&quot; content=&quot;Gra internetowa Parafia.biz - podbij wirtualną  rzeczywistość - gra przeglądarkowa przez www&quot; /&gt;
        ///	&lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParafiaBizBankEmptyContent {
            get {
                return ResourceManager.GetString("ParafiaBizBankEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Gra internetowa Parafia.biz - podbij wirtualną  rzeczywistość - gra przeglądarkowa przez www&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;link href=&quot;https://plus.google.com/102903768040082646276&quot; rel=&quot;publisher&quot;/&gt;
        ///    &lt;meta property=&quot;og:site_name&quot; content=&quot;Parafia.biz&quot; /&gt;
        ///	&lt;meta property=&quot;og:title&quot; content=&quot;Parafia.biz&quot; /&gt;
        ///	&lt;meta property=&quot;og:description&quot; content=&quot;Gra internetowa Parafia.biz - podbij wirtualną  rzeczywistość - gra przeglądarkowa przez www&quot; /&gt;
        ///	&lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParafiaBizBankFullContent {
            get {
                return ResourceManager.GetString("ParafiaBizBankFullContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Gra internetowa Parafia.biz - podbij wirtualną  rzeczywistość - gra przeglądarkowa przez www&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta property=&quot;og:site_name&quot; content=&quot;Parafia.biz&quot; /&gt;
        ///	&lt;meta property=&quot;og:title&quot; content=&quot;Parafia.biz&quot; /&gt;
        ///	&lt;meta property=&quot;og:description&quot; content=&quot;Gra internetowa Parafia.biz - podbij wirtualną  rzeczywistość - gra przeglądarkowa przez www&quot; /&gt;
        ///	&lt;meta property=&quot;og:image&quot; content=&quot;http://parafia.biz/img/fb_like.jpg&quot; /&gt;
        ///	&lt;meta pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParafiaBizExpeditionsContent {
            get {
                return ResourceManager.GetString("ParafiaBizExpeditionsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Gra internetowa Parafia.biz - podbij wirtualną  rzeczywistość - gra przeglądarkowa przez www&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta property=&quot;og:site_name&quot; content=&quot;Parafia.biz&quot; /&gt;
        ///	&lt;meta property=&quot;og:title&quot; content=&quot;Parafia.biz&quot; /&gt;
        ///	&lt;meta property=&quot;og:description&quot; content=&quot;Gra internetowa Parafia.biz - podbij wirtualną  rzeczywistość - gra przeglądarkowa przez www&quot; /&gt;
        ///	&lt;meta property=&quot;og:image&quot; content=&quot;http://parafia.biz/img/fb_like.jpg&quot; /&gt;
        ///	&lt;meta pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParafiaBizUnitsContent {
            get {
                return ResourceManager.GetString("ParafiaBizUnitsContent", resourceCulture);
            }
        }
    }
}
